version: '3.8'

services:
  web:
    build: .
    ports:
      - "5002:5000"
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: